controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - rgripper_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: pick
  - group: hand
    pose: open