# Controller to control robot arm joints
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1 ,joint2 ,joint3 ,joint4 ,joint5]
  constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.7
      joint1: {trajectory: 0.1, goal: 1}
      joint2: {trajectory: 0.1, goal: 1}
      joint3: {trajectory: 0.1, goal: 1}
      joint4: {trajectory: 0.1, goal: 1}
      joint5: {trajectory: 0.1, goal: 1}

# Controller to control gripper joints
gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Lgripperjoint, rgripper_joint]
  constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.7
      Lgripperjoint: {trajectory: 0.1, goal: 1}

# Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
