# Controller to control robot arm joints
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1 ,joint2 ,joint3 ,joint4 ,joint5]

# Controller to control gripper joints
gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [rgripper_joint]
# Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
